### ISSUE TITLE
Where is scull.c?

### ISSUE THREAD

**Issue by paulelong** [duxing2007/ldd3-examples-3.x#18]
I want to play with the code for Chapter 3.  The scr layout file mentions that chapter 3 scull.c is in the root.  There aren't any files in the root, but some of the others are in the misc directories, but not scull.c.  It also seems to be missing from the original tarball from o'reilly and other GitHub versions.  

Am I missing something obvious?  
Thanks, Paul

**Comment by paulelong** [comment]
I see now that the project is in the directory scull, not scull.c.  And the project contains many more sources files than were discussed in the chapter, which threw me off.

**Comment by duxing2007** [comment]
You‘ve’ fixed layout file.Thanks
