### ISSUE TITLE
Remote branch names include name of remote

### ISSUE THREAD

**Issue by NGenetzky** [duxing2007/ldd3-examples-3.x#21]
First, thank you for your excellent work.

---

I believe you would be better off having a branches named `linux-3.18.y` rather than `origin/linux-3.18.y`. The issue arises from pushing with the following (from `Documentation/git-misc.md`):
```
git push origin origin/linux-3.18.y:origin/linux-3.18.y
```

Instead just do:
```
git push origin linux-3.18.y:linux-3.18.y
```

**Comment by duxing2007** [comment]
Thanks.  Fixed now.
