### ISSUE TITLE
make not working on centos 6.8

### ISSUE THREAD

**Issue by chakpongchung** [duxing2007/ldd3-examples-3.x#3]
make: *** /lib/modules/3.10.0-327.36.3.el7.x86_64/build: No such file or directory.  Stop.

[root@localhost ldd3-examples-3.x-origin-linux-3.10.y]# uname -r
3.10.0-327.36.3.el7.x86_64

**Comment by KarthikNayak** [comment]
You need to have kernel headers. `yum install kernel-devel` should do the trick if I'm not wrong :D

**Comment by duxing2007** [comment]
see above
