### ISSUE TITLE
scullc not working on kernel 4.4

### ISSUE THREAD

**Issue by chakpongchung** [duxing2007/ldd3-examples-3.x#5]
cpchung:scullc$ sudo ./scullc_load 
insmod: ERROR: could not insert module ./scullc.ko: Invalid module format
cpchung:scullc$ git branch
* (HEAD detached at origin/master)
  master
  origin/linux-4.1.y

**Comment by duxing2007** [comment]
Sorry about that I  don't have time to fix for kernel 4.4 currently.
I'll fix it before 2017-02-15.

**Comment by chakpongchung** [comment]
Thank you Du. If it works on 4.1, which minor version does it work on? on ubuntu or centos?

I may not need the latest version.

**Comment by chakpongchung** [comment]
There is a good news for you.

On ubuntu 14.04 with the following kernel, all folders compile without error.

cpchung:ldd3-examples-3.x$ uname -r
4.2.0-42-generic

cpchung:ldd3-examples-3.x$ git branch
* master

**Comment by duxing2007** [comment]
fix
