### ISSUE TITLE
Repository name dose not sufficiently represent project

### ISSUE THREAD

**Issue by tcharding** [duxing2007/ldd3-examples-3.x#6]
Awesome work on this port effort. Current repository name does not fully represent the code base since there are branches for kernel versions 4.x. This is a useful project and would be a shame if people missed it because of the 3.x in the name.

**Comment by duxing2007** [comment]
github do not support change Repository name.
I just change "Description"
port ldd3 source code examples **after** linux 3.x Edit

**Comment by tcharding** [comment]
Repository name change is supported. If you go to settings and start typing in the repository name box it becomes non-greyed out.

**Comment by duxing2007** [comment]
Thanks. But If I changed repository name, those links on other site will become invalid.

**Comment by tcharding** [comment]
Good point

**Comment by telent** [comment]
For what it's worth, I just tested this on one of my own repos, and it appears that github will do a 301 redirect from the old URL to the new one.
